# Generated by Django 5.1.1 on 2025-08-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_banner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packageschedule",
            name="schedule_photos",
        ),
        migrations.RemoveField(
            model_name="tourpackage",
            name="photos",
        ),
        migrations.CreateModel(
            name="SchedulePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="schedule_photos/")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.packageschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourPackagePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="package_photos/")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.tourpackage",
                    ),
                ),
            ],
        ),
    ]
